import { Amplify } from 'aws-amplify';
import outputs from '../../amplify_outputs.json';

// `amplify_outputs.json` is generated by `npx ampx sandbox` (local dev) or by
// the Amplify Hosting pipeline build. It contains Cognito + AppSync wiring.
Amplify.configure(outputs);
